# Working with NumPy

When you start working with numeric computations, you'll soon start wanting to work with sequence of numbers like in **vectors**, a collection of vectors like in **matrices**, and potentially even higher dimensional structures like **tensors**. 

While you could imagine using **a list** to represent a vector, as in:

In [1]:
v1 = [1, 2, 3]
v2 = [4, 5, 6]

Performing very common vector operations like vector additions and dot products can be cumbersome:

In [2]:
v3 = v1 + v2
print(v3)

[1, 2, 3, 4, 5, 6]


In [3]:
def vector_add(v1, v2):
    v3 = []
    for i in range(len(v1)):
        v3.append(v1[i] + v2[i])
    return v3

In [4]:
vector_add(v1, v2)

[5, 7, 9]

Fortunately, you can get access to a very powerful numeric array library for Python by installing **NumPy** package. If you have used Anaconda distribution, then your Python already comes with **NumPy** installed!

To start using the **NumPy** package, you have to import them:

In [5]:
import numpy as np

# Creating a NumPy array

You can convert a list into **a NumPy array** that supports more complex numeric operations:

In [6]:
a = np.array([1, 2, 3])

In [7]:
a

array([1, 2, 3])

In [8]:
b = np.array([4, 5, 6])

Unlike lists, NumPy arrays supports mathematical operations like that for vectors and matrices:

sum of two vectors

In [9]:
a + b

array([5, 7, 9])

dot product

In [10]:
a @ b

32

Above you have created a vector or more specifically a **1-D array**

In [11]:
x = np.array([1, 2, 3, 4, 5])

You can look at an array's dimension with its `ndim` property

In [12]:
x.ndim

1

and get its **shape** with `shape` property

In [13]:
x.shape

(5,)

You can create a **2-D array** by turning a **list of list** into an array.

In [14]:
y = np.array([[0, 1, 2], [3, 4, 5]])  # 2 x 3 array

y

array([[0, 1, 2],
       [3, 4, 5]])

In [15]:
y.ndim

2

In [16]:
y.shape

(2, 3)

# Functions for creating arrays

While you can enter elemetns of array one-by-one, it is far more common to use one of NumPy's special functions for creating an array.

## Range of integers

Just like `range()` function to create an iterable, ther is `np.arange` that let's you create a sequence of integers as a NumPy array

In [17]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [18]:
for i in range(10):
    print(i)

0
1
2
3
4
5
6
7
8
9


In [19]:
np.arange(5, 10)

array([5, 6, 7, 8, 9])

In [20]:
np.arange(3, 30, 2)

array([ 3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29])

In [21]:
for i in range(3,30,2):
    print(i)

3
5
7
9
11
13
15
17
19
21
23
25
27
29


## Specifying start, ending and number of items

Alternatively, you might want to specify the start and end, and also specify **how many elements** should fit in that range, equally spaced apart:

In [22]:
np.linspace(0, 1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [23]:
np.linspace(0, 1, 100)

array([0.        , 0.01010101, 0.02020202, 0.03030303, 0.04040404,
       0.05050505, 0.06060606, 0.07070707, 0.08080808, 0.09090909,
       0.1010101 , 0.11111111, 0.12121212, 0.13131313, 0.14141414,
       0.15151515, 0.16161616, 0.17171717, 0.18181818, 0.19191919,
       0.2020202 , 0.21212121, 0.22222222, 0.23232323, 0.24242424,
       0.25252525, 0.26262626, 0.27272727, 0.28282828, 0.29292929,
       0.3030303 , 0.31313131, 0.32323232, 0.33333333, 0.34343434,
       0.35353535, 0.36363636, 0.37373737, 0.38383838, 0.39393939,
       0.4040404 , 0.41414141, 0.42424242, 0.43434343, 0.44444444,
       0.45454545, 0.46464646, 0.47474747, 0.48484848, 0.49494949,
       0.50505051, 0.51515152, 0.52525253, 0.53535354, 0.54545455,
       0.55555556, 0.56565657, 0.57575758, 0.58585859, 0.5959596 ,
       0.60606061, 0.61616162, 0.62626263, 0.63636364, 0.64646465,
       0.65656566, 0.66666667, 0.67676768, 0.68686869, 0.6969697 ,
       0.70707071, 0.71717172, 0.72727273, 0.73737374, 0.74747

## Common starting array: `ones`, `zeros`, and `random`

You would often want to start with an array of specified sizes (e.g. 3 x 3 matrix) initialized with 0s, 1s, or perhaps random numbers.

### initialize to 0

In [24]:
np.zeros((3, 3))  # be careful - you pass in a tuple specifying the shape

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

### initialize to 1

In [25]:
np.ones((3, 4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

### randomly initialized

In [26]:
np.random.rand(4, 2)  # random number uniformly drawn between 0 and 1

array([[0.56044869, 0.73712218],
       [0.4199315 , 0.46270444],
       [0.11299876, 0.88360749],
       [0.28534243, 0.24483812]])

In [27]:
np.random.randn(4, 2)  # random number drawn from standard normal distribution

array([[ 0.53788277, -0.70854517],
       [-0.46592496,  1.42834689],
       [ 0.89301795,  0.0443833 ],
       [ 1.55704043,  0.40051387]])

## Other special matrices: identity matrix and diagonal matrix

On other occasions, you'd want to create an identity matrix (matrix where only diagonal elements are 1s) and diagonal matrix (matrix where only diagonal elements are non-zeros)

In [28]:
np.eye(4)  # 4 x 4 identity matrix

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [29]:
np.diag([1, 2, 3, 4]) # 4 x 4 matrix with 1, 2, 3, 4 as the diagonal entries

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

## Reshaping arrays

You can create an array in one shape and then later **reshape** it. This can be a neat trick for creating a higher dimensional array with sequential content:

Create a flat sequential array

In [30]:
x = np.arange(15)

x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

Now reshape it into 3 x 5

In [31]:
x.reshape(3, 5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

We are going to revisit array shape manipulation in much more details later.

# Indexing and slicing arrays

You can index and slice a 1-D array just like you would for a list

In [32]:
a = np.arange(10)

In [33]:
a[0]  # first element

0

In [34]:
a[-1] # last element

9

In [35]:
a[3:8] # slicing

array([3, 4, 5, 6, 7])

In [36]:
a[::-1] # reversing

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

When working with **multidimensional arrays**, you have more choices with indexing:

In [37]:
a = np.arange(12).reshape(3, 4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [38]:
a[0] # selects the first row

array([0, 1, 2, 3])

In [39]:
a[-1] # selects the last row

array([ 8,  9, 10, 11])

In [40]:
a[:2] # slice first two rows

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [41]:
a[0, 1] # selects row 0, column 1

1

In [42]:
a[2, 2]

10

In [43]:
a[1, :3] # slice first row, first three columns

array([4, 5, 6])

In [44]:
a[:, 2] # get column 2

array([ 2,  6, 10])

Slicing multiple dimensions together

In [45]:
a = np.arange(16).reshape(4, 4)

In [46]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [47]:
a[1:3, 1:4]

array([[ 5,  6,  7],
       [ 9, 10, 11]])

# Modifying arrays

Just like list, NumPy arrays are **mutable** - meaning, you can change its content after the creation.

In [48]:
x = np.zeros((3, 5))
x

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

## Change one element at a time

In [49]:
x[1, 2] = 3

In [50]:
x

array([[0., 0., 0., 0., 0.],
       [0., 0., 3., 0., 0.],
       [0., 0., 0., 0., 0.]])

## Change an entire row:

In [51]:
x[0] = 4

In [52]:
x

array([[4., 4., 4., 4., 4.],
       [0., 0., 3., 0., 0.],
       [0., 0., 0., 0., 0.]])

## Change an entire column:

In [53]:
x[:, -1] = 5

In [54]:
x

array([[4., 4., 4., 4., 5.],
       [0., 0., 3., 0., 5.],
       [0., 0., 0., 0., 5.]])

## Placing another list into an array

In [55]:
x[-1] = [10, 20, 30, 40, 50]

In [56]:
x

array([[ 4.,  4.,  4.,  4.,  5.],
       [ 0.,  0.,  3.,  0.,  5.],
       [10., 20., 30., 40., 50.]])

In [57]:
x[0] = [1, 2, 3]

ValueError: cannot copy sequence with size 3 to array axis with dimension 5

## Copies vs Views

You saw that you can use indexing and slicing to assign values into an array. But what would happen if you slice an array, and then assign values into an index in that array?

In [58]:
x = np.arange(15).reshape(3, 5)

x

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [59]:
r = x[1] # second row

In [60]:
r[3] # 4th value in the second row

8

You can modify a value in the 1-D array.

In [61]:
r[3] = 100

In [62]:
r

array([  5,   6,   7, 100,   9])

What happens in the original array?

In [63]:
x

array([[  0,   1,   2,   3,   4],
       [  5,   6,   7, 100,   9],
       [ 10,  11,  12,  13,  14]])

Notice that changing values of `r` results in changes in `x`!

This is because **slicing an array** returns what's called a **view** of an array. View is a bit like a viewing window - you are only seeing a part of the original array, but you are nevertheless still looking at the array!

A handful of NumPy operations (including slicing) returns a view and thus can be a convenient way to continue to work with the original array and often can save memory by avoiding unnecessary copies of data. 

However, there will be situations that you want to pass a copy of the array so that you don't have to worry about your original array accenditanlly getting modified. You can use `copy()` method in these cases.

In [64]:
x = np.arange(15).reshape(3, 5)

r = x[0].copy()

# update all elements of r
r[:] = r * 100

print('r=')
print(r)
print('x=')
print(x)

r=
[  0 100 200 300 400]
x=
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


# Working with arrays

## Elementwise operations

You can perform **elementwise** operations easily with NumPy array

In [65]:
x = np.arange(5)
x

array([0, 1, 2, 3, 4])

In [66]:
x + 3

array([3, 4, 5, 6, 7])

In [67]:
x**2

array([ 0,  1,  4,  9, 16])

In [68]:
y = np.ones(5) + 5
y

array([6., 6., 6., 6., 6.])

In [69]:
x - y

array([-6., -5., -4., -3., -2.])

In [70]:
2 ** x

array([ 1,  2,  4,  8, 16])

In [71]:
np.sqrt(x)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ])

### Multiplying arrays

When you multiply arrays, they do **not** perform matrix multiplication

In [72]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[1, 0], [0, 1]])

In [78]:
# elementiwise multiplication
a * b

array([[1, 0],
       [0, 4]])

To get matrix multiplcation, you want to use `@` operator

In [79]:
# matrix multiplication
a @ b

array([[1, 2],
       [3, 4]])

## Speed of operations

Aside from being far easily to perform operations on, operations on NumPy arrays are much faster than on lists!

Let's compare the time of squaring a sequence of numbers from 0 to 99 (inclusive)

We'll use `%%timeit` Jupyter Magic to measure the average time it takes to complete the operation.

### List

In [80]:
x = list(range(100))

In [81]:
%%timeit
x2 = []
for v in x:
    x2.append(v**2)

34.5 µs ± 2.16 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)


#### Using list comprehension

There is a bit more succinct way to express a loop based operations like above using what's known as **list comprehension**.

In [83]:
%%timeit
x2 = [v**2 for v in x] # this is equivalent to the above code

30.8 µs ± 2.49 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)


List comprehension can be slightly faster than full-fledge for-loops.

### Numpy array

In [84]:
x = np.arange(100)

In [85]:
%%timeit
x2 = x**2

715 ns ± 8.56 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


You should see that NumPy is usually quite a bit faster!

## Comparisons

You can perform comparisons on arrays to get an array of boolean values.

In [86]:
a = np.array([1, 2, 3, 4])
b = np.array([4, 2, 2, 4])

#### Equality

In [87]:
a == b

array([False,  True, False,  True])

In [88]:
a == 3

array([False, False,  True, False])

#### Inequality

In [89]:
a > b

array([False, False,  True, False])

In [90]:
a < 4

array([ True,  True,  True, False])

### Universal functions (ufuncs)

NumPy also comes with a lot of functions that works on element-by-element basis, and these are called **universal functions** or ufuncs for short. Examples include `np.sqrt`, `np.sin`, and `np.log`

In [91]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [92]:
np.sqrt(a)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [93]:
np.sin(a)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849])

In [94]:
np.log(a)

/Users/shanshen/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log
  """Entry point for launching an IPython kernel.


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458])

### Transposition

When working with a 2-D array (matrix), you would often encounter a need to **transpose** an array. You can achieve this with `.T`

In [96]:
a = np.array([[1, 2, 3], [4, 5, 6]])
a

array([[1, 2, 3],
       [4, 5, 6]])

In [97]:
a.T # returns a transposed VIEW

array([[1, 4],
       [2, 5],
       [3, 6]])

In [99]:
a.T?

Type:            ndarray
String form:    
[[  1   4]
 [  2   5]
 [100   6]]
Length:          3
File:            ~/anaconda3/lib/python3.6/site-packages/numpy/__init__.py
Docstring:       <no docstring>
Class docstring:
ndarray(shape, dtype=float, buffer=None, offset=0,
        strides=None, order=None)

An array object represents a multidimensional, homogeneous array
of fixed-size items.  An associated data-type object describes the
format of each element in the array (its byte-order, how many bytes it
occupies in memory, whether it is an integer, a floating point number,
or something else, etc.)

Arrays should be constructed using `array`, `zeros` or `empty` (refer
to the See Also section below).  The parameters given here refer to
a low-level method (`ndarray(...)`) for instantiating an array.

For more information, refer to the `numpy` module and examine the
methods and attributes of an array.

Parameters
----------
(for the __new__ method; see Notes below)

shape : tuple of ints
  

Notice that transposition returns a **view**, and thus modifying the returned array results in the modification of the original:

In [100]:
b = a.T

b[-1, 0] = 100

In [101]:
b

array([[  1,   4],
       [  2,   5],
       [100,   6]])

In [102]:
a

array([[  1,   2, 100],
       [  4,   5,   6]])

# Reductions and statistics

One very common type of computations on array is the **reduction** - an operations that results in smaller array as results. Examples include summation, mean, max and min.

In [103]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [104]:
np.sum(x)

45

Many operations are also available as methods on the array:

In [105]:
x.sum()

45

When working with higher dimensional array (dim >= 2), you can actually specify the axis to perform reduction over:

In [106]:
x = np.array([[1, 1], [2, 2]])
x

array([[1, 1],
       [2, 2]])

In [107]:
x.sum(axis=0) # reduces over axis=0 -> sum over rows

array([3, 3])

In [108]:
x.sum(axis=1) # reduces over axis=1 -> sum over columns

array([2, 4])

In [109]:
y = np.array([[1, 2, 8], [4, -3, 5]])

y

array([[ 1,  2,  8],
       [ 4, -3,  5]])

In [110]:
y.max(axis=0) # maximum over rows

array([4, 2, 8])

In [111]:
y.max() # maximum overall

8

### Statistics

Statistics computations are example of reductions, and common computations such as mean, median, and standard deviations are provided:

In [112]:
x = np.array([1, 2, 3, 5, 10, -5])

In [113]:
x.mean()

2.6666666666666665

In [114]:
np.median(x)  # there is no x.median

2.5

In [115]:
x.std()

4.4969125210773475

In [117]:
x.std?

Docstring:
a.std(axis=None, dtype=None, out=None, ddof=0, keepdims=False)

Returns the standard deviation of the array elements along given axis.

Refer to `numpy.std` for full documentation.

See Also
--------
numpy.std : equivalent function
Type:      builtin_function_or_method


In [118]:
np.std?

Signature: np.std(a, axis=None, dtype=None, out=None, ddof=0, keepdims=<class 'numpy._globals._NoValue'>)
Docstring:
Compute the standard deviation along the specified axis.

Returns the standard deviation, a measure of the spread of a distribution,
of the array elements. The standard deviation is computed for the
flattened array by default, otherwise over the specified axis.

Parameters
----------
a : array_like
    Calculate the standard deviation of these values.
axis : None or int or tuple of ints, optional
    Axis or axes along which the standard deviation is computed. The
    default is to compute the standard deviation of the flattened array.

    .. versionadded:: 1.7.0

    If this is a tuple of ints, a standard deviation is performed over
    multiple axes, instead of a single axis or all the axes as before.
dtype : dtype, optional
    Type to use in computing the standard deviation. For arrays of
    integer type the default is float64, for arrays of float types it is
    t

Let's use a random samples of Normal distribution:

In [122]:
# 100 samples of Normal distribution
x = np.random.randn(10000)

In [123]:
x.mean()

0.0117973984535455

In [124]:
x.std()

1.0005677947813896

# Fancy indexing

We have already looked at how to index into an array with an integer or a tuple of integers:

In [125]:
a = np.arange(12).reshape(2, 2, 3)
a

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]]])

In [126]:
a[0]

array([[0, 1, 2],
       [3, 4, 5]])

In [127]:
a[0, 1, 2]

5

In [186]:
b = np.arange(1,13).reshape(2, 2, 3)
b

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

Let's now look at a more advanced or **fancy** indexing:

## Indexing with boolean

Probably by far the most useful fancy indexing is the boolean indexing. Given an array:

In [128]:
a = np.array([-5, 10, 6, -8, -2, 3, 0])

suppose that we want to take all negative numbers change them to 0, an operation sometimes referred to as *rectification*. We can actually use a for-loop just like on a list:

In [129]:
for i in range(len(a)):
    if a[i] < 0:
        a[i] = 0
a

array([ 0, 10,  6,  0,  0,  3,  0])

While this works, this now uses a for loop and thus not super quick. Earlier, we saw that we can get an array of `True` and `False` with comparison operators

In [130]:
a = np.array([-5, 10, 6, -8, -2, 3, 0])

In [131]:
a < 0

array([ True, False, False,  True,  True, False, False])

It turns out that you can **index into an array with a boolean array**:

In [132]:
a[a < 0] # selects the negative entries

array([-5, -8, -2])

And finally, you can use the result as target of assignment directly!

In [133]:
a[a < 0] = 0   # make all negative numbers 0

a

array([ 0, 10,  6,  0,  0,  3,  0])

In [140]:
np.nonzero(a)

(array([1, 2, 5]),)

In [143]:
np.where(a > 3)

(array([1, 2]),)

A beauty in this is that you can use this on an array of arbitrary dimensions!

In [144]:
x = np.array([[1, -5, 3, 10, 7, -5],[-5, 8, 9, -1, -10, -4]])
x

array([[  1,  -5,   3,  10,   7,  -5],
       [ -5,   8,   9,  -1, -10,  -4]])

In [145]:
x < 0

array([[False,  True, False, False, False,  True],
       [ True, False, False,  True,  True,  True]])

In [146]:
x[x < 0]

array([ -5,  -5,  -5,  -1, -10,  -4])

In [147]:
x[x < 0] = 0

In [148]:
x

array([[ 1,  0,  3, 10,  7,  0],
       [ 0,  8,  9,  0,  0,  0]])

## Indexing with an array of integers

You can use an array of integers as index into an array:

In [149]:
a = np.arange(0, 100, 10)
a

array([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [150]:
a[[2, 3, 2, 4, 2]]

array([20, 30, 20, 40, 20])

In [151]:
a[[2, 3, 9]]

array([20, 30, 90])

You can use this to assign:

In [152]:
a[[2, 3, 9]] = -100

In [153]:
a

array([   0,   10, -100, -100,   40,   50,   60,   70,   80, -100])

## Sorting an array

Given an array, you can get a sorted **copy** using `np.sort`

In [154]:
x = np.array([1, 4, 3, 0, 5])

In [157]:
y = np.sort(x)
x

array([1, 4, 3, 0, 5])

`.sort` method sorts the array **in place**

In [161]:
x.sort()

In [162]:
x

array([0, 1, 3, 4, 5])

For higher dimension array, you can specify the **dimension to sort along**

In [163]:
a = np.array([[1, 8, 4, 5], [3, 9, 2, 4], [1, 2, 3, 0]])
a

array([[1, 8, 4, 5],
       [3, 9, 2, 4],
       [1, 2, 3, 0]])

In [164]:
np.sort(a, axis=0) # sort within columns (that is, sort along the rows)

array([[1, 2, 2, 0],
       [1, 8, 3, 4],
       [3, 9, 4, 5]])

In [165]:
np.sort(a, axis=1) # sort within rows (that is, sort along the columns) 

array([[1, 4, 5, 8],
       [2, 3, 4, 9],
       [0, 1, 2, 3]])

# On the tangent: keyword arguments

Notice that in some cases, we specify the name of the parameter when passing in an argument, for example in the case of `x.mean(axis=5)`. In Python, you can actually give value to the specific parameter by using **keyword arguments** notation.

For example, consider the following function:

In [166]:
def greeting(name, message='Hello!', n=1):
    for i in range(n):
        print('{} {}'.format(message, name))

In [167]:
greeting('Edgar')

Hello! Edgar


In [168]:
greeting('Edgar', 'Morning!')

Morning! Edgar


In [169]:
greeting('Edgar', 'Morning!', 10)

Morning! Edgar
Morning! Edgar
Morning! Edgar
Morning! Edgar
Morning! Edgar
Morning! Edgar
Morning! Edgar
Morning! Edgar
Morning! Edgar
Morning! Edgar


What if I wanted to use the default for `message` (that is, "Hello!") but wanted to specify the number of times the message prints? You can use keyword arguments!

In [170]:
greeting('Edgar', n=5)

Hello! Edgar
Hello! Edgar
Hello! Edgar
Hello! Edgar
Hello! Edgar


Hence, keyword arguments are useful if you want to change the non-default behavior for certain arguments but use the default arguments for the rest!

Note that because `name` doesn't have a default value, you **must** always specify the value. However, you can actually use keyword arguments to change the position at which you specify its value!

In [171]:
greeting(n=10, name='John')

Hello! John
Hello! John
Hello! John
Hello! John
Hello! John
Hello! John
Hello! John
Hello! John
Hello! John
Hello! John


In [172]:
greeting(n=10, name='John', message='Hi!')

Hi! John
Hi! John
Hi! John
Hi! John
Hi! John
Hi! John
Hi! John
Hi! John
Hi! John
Hi! John


# Broadcasting

One very interesting, potentially confusing but ultimately useful feature of NumPy array is **broadcasting**. To understand what it is all about, let's start at the real basics - adding two arrays

We already saw that you can add two arrays of same size, and the addition occurs **element wise** as expected.

In [173]:
a = np.array([1, 2, 3])
b = np.array([1, 1, 1])

a + b

array([2, 3, 4])

You can also create a *column vector* by preparing a 2-D array of shape N x 1

In [174]:
a = np.array([[1], [2], [3]])
b = np.array([[1], [1], [1]])

In [175]:
a

array([[1],
       [2],
       [3]])

In [177]:
b

array([[1],
       [1],
       [1]])

Adding them is not a problem

In [178]:
a + b

array([[2],
       [3],
       [4]])

Now what would happen if we take the following two arrays:

In [179]:
a = np.array([[1, 2, 3]])
b = np.array([[1], [1], [1]])

In [180]:
a

array([[1, 2, 3]])

In [181]:
b

array([[1],
       [1],
       [1]])

and add them?

In terms of matrix algebra, you shouldn't be able to add two matrices of differing sizes, but...

In [182]:
a + b

array([[2, 3, 4],
       [2, 3, 4],
       [2, 3, 4]])

What just happened?! Well, **broadcasting** happened.

## Array shape manipulation

To completely harness the power of broadcasting, it becomes critical that you can manipulate the exact shape of an array.

## Flattening an array

Sometimes you want to flatten out an array into a long vector. You achieve this with `ravel`.

In [194]:
a = np.array([[1, 2, 3], [4, 5, 6]])
a

array([[1, 2, 3],
       [4, 5, 6]])

In [195]:
b = a.ravel()
b

array([1, 2, 3, 4, 5, 6])

Be ware that this returns a **view**

In [196]:
b[0] = 100

In [197]:
a

array([[100,   2,   3],
       [  4,   5,   6]])

Also pay special attention to the order of traversal of elements when flatenning - in Python, the **last dimension ravels out first**.

## Reshaping

We already saw that we can take a flat array and turn it into higher dimension array as long as the number of elements matches:

In [198]:
a = np.arange(24)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [203]:
b = a.reshape([2, 3, 4])

In [205]:
b[0,0,:]

array([0, 1, 2, 3])

You can actually take a non-flat array and change it's shape as well:

In [206]:
x = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]])
x

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [207]:
x.reshape([3, 4])

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

## Adding and reducing dimensions

Sometimes, you want to add a dimension into your array, most likely for the purpose of broadcasting.

Say that you want to add each of values `[-1, 0, 1]` to an array `[1, 2, 3, 4]`, yielding `[0, 1, 2, 3]`, `[1, 2, 3, 4]`, and `[2, 3, 4, 5]`. This could be done with broadcasting:

In [208]:
x = np.array([-1, 0, 1])
y = np.array([1, 2, 3, 4])

However, as it stands, you cannot broadcast them together because they are both 1-D arrays.

In [209]:
x

array([-1,  0,  1])

In [210]:
x.shape

(3,)

In [211]:
y

array([1, 2, 3, 4])

In [212]:
y.shape

(4,)

In [213]:
x + y

ValueError: operands could not be broadcast together with shapes (3,) (4,) 

What you want to do, is to make them both into 2-D array, and make one a column vector and the other a row vector, so you can broadcast them together.

In [214]:
x = x[np.newaxis, :] # add a singleton first dimension

In [215]:
x

array([[-1,  0,  1]])

In [216]:
x.shape

(1, 3)

In [217]:
y = y[:, np.newaxis] # add a singleton second dimension

In [218]:
y

array([[1],
       [2],
       [3],
       [4]])

In [219]:
y.shape

(4, 1)

Now you can add them for broadcasting

In [220]:
x + y

array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4],
       [3, 4, 5]])

## Squeeze dimensions

Given an array, you can **squeeze out** singleton dimensions from an array with `.squeeze()` method.

In [221]:
x = np.random.randn(4, 1, 1, 3, 1)

In [222]:
x

array([[[[[-0.97480607],
          [ 0.64385167],
          [-0.63976534]]]],



       [[[[-0.24444674],
          [ 1.98684846],
          [ 0.27792004]]]],



       [[[[ 0.83327115],
          [ 0.39865831],
          [-0.15916238]]]],



       [[[[ 2.01503869],
          [-0.15753149],
          [-0.92952111]]]]])

In [223]:
x.shape

(4, 1, 1, 3, 1)

In [224]:
y = x.squeeze()

In [225]:
y

array([[-0.97480607,  0.64385167, -0.63976534],
       [-0.24444674,  1.98684846,  0.27792004],
       [ 0.83327115,  0.39865831, -0.15916238],
       [ 2.01503869, -0.15753149, -0.92952111]])

In [226]:
y.shape

(4, 3)

# NumPy Exercises

Here are a few NumPy array exercises to practice your array creation and manipulation skills.

### 1. Create a vector of size 10 filled with 0s.

In [228]:
a = np.zeros(10)
a

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

### 2. Create a vector of integers starting from 0 and ending at 50

In [232]:
a = np.arange(0, 51)
np.shape(a)

(51,)

### 3. Reverse the following vector

In [238]:
x = np.array([1, 2, 3, 4, 5])

# do something on x to reverse it! Hint: slicing syntax with step?
x = x[::-1]
x

array([5, 4, 3, 2, 1])

### 4. Create a 4 x 4 matrix with values ranging from 0 to 15

In [240]:
a = np.arange(0, 16).reshape(4, 4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

### 5. Create a 4 x 4 matrix with values ranging from 3 to 18

In [241]:
a = np.arange(3, 19).reshape(4, 4)
a

array([[ 3,  4,  5,  6],
       [ 7,  8,  9, 10],
       [11, 12, 13, 14],
       [15, 16, 17, 18]])

### 6. Create 5 x 5 identity matrix

In [246]:
a = np.eye(5, 5)
a

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

### 7. Create 2 x 2 x 3 array with random values

In [245]:
a = np.random.rand(2, 2, 3)
a

array([[[0.90362427, 0.45631708, 0.48787649],
        [0.47125584, 0.50321627, 0.81931151]],

       [[0.12241091, 0.08242603, 0.49846857],
        [0.99939255, 0.95001548, 0.53294338]]])

### 8. Find the pairwise difference between each element of a vector

Express the pairwise difference as a matrix

So for `[1, 2, 3]`, pairwise difference matrix is:

```
[[0, 1, 2],
[-1, 0, 1],
[-2, -1, 0]]
```

Hint 2: ...broadcasting?

In [250]:
a = np.arange(0, 4)
a1 = a[np.newaxis, :]
np.shape(a1)

(1, 4)

In [256]:
diff = a1 - a1.T
diff

array([[ 0,  1,  2,  3],
       [-1,  0,  1,  2],
       [-2, -1,  0,  1],
       [-3, -2, -1,  0]])